version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - custom-5807
  /features/:
    -
      - custom-3119
  /utility/:
    -
      - custom-2396
  /above/:
    -
      - custom-3719
    -
      - contenttabs-3854
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
      extra:
        -
          style: 'max-height:500px;'
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'padding: 1.5em 0;'
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'display:none'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'display:none;'
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#f0f0f0;'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: disable
      items:
        -
          image: 'gantry-media://header/img01.jpg'
          title: 'The Canadian Federation of Engineering Students'
          desc: ''
          link: ''
          linktext: ''
          buttonclass: ''
          name: 'Item 1'
  custom-5807:
    title: Intro
    attributes:
      html: "<div class=\"fp-intro\">\n<h3>The Canadian Federation of Engineering Students (CFES) is a national, bilingual organization that represents approximately 60,000 engineering students across Canada. Offering services ranging from leadership development conferences, to technical skill competitions, a national student magazine and other outreach efforts, the CFES aims to provide opportunities in support of an all-encompassing education for engineering students in Canada to become unparalleled professionals in their field.</h3>\n<p id=\"mission-vision\"></p>\n</div>"
    block:
      variations: center
  custom-3119:
    title: 'Mission & Vision'
    attributes:
      html: "<div class=\"fp-intro\">\n<h2 class=\"g-title\">Mission & Vision</h2>\n\t<p>The CFES supports growth and communication within its members to ensure their moral, intellectual,  cultural, academic, social and economic well-being. The Federation represents and promotes Canadian undergraduate engineering students on a national and international level. The CFES will not align itself with any political partisan movement.</p>\n\t<p> The goal of the CFES is to solicit, represent, organize and exchange views, information and activities pertinent to the goals of the members at a national level as to ensure their moral, intellectual, cultural, academic, social and economic well-being, and to improve the quality and scope of Canadian engineering education. The means by which this will be done are:</p>\n\t<ol>\n\t\t<li>Offering bilingual opportunities which foster the development of the following facets of an engineering education:\n\t\t<ul>\n\t\t\t<li>Leadership</li>\n\t\t\t<li>Professional and Ethical Qualities</li>\n\t\t\t<li>Engineering Identity</li>\n\t\t\t<li>Technical Proficiency</li>\n\t\t\t<li>Communication</li>\n\t\t</ul></li>\n\t\t<li>Provides representation on issues relevant to engineering students in Canada and affiliate itself with any organization pursuing the same goals,</li>\n\t\t<li>Promotes the free exchange of ideas and experiences to support the constant evolution of student environments across Canada.</li>\n\t</ol>\n</div>"
    block:
      variations: title-center
  custom-2396:
    title: stats
    attributes:
      html: "<div class=\"fp-features\">\n    <div class=\"g-grid\">\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">52</h4>\n                    <p class=\"card-text\">REPRESENTED MEMBER SOCIETIES</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">8</h4>\n                    <p class=\"card-text\">ANNUAL EVENTS & SERVICES</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">48</h4>\n                    <p class=\"card-text\">YEARS OF OPERATION</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">60,000</h4>\n                    <p class=\"card-text\">STUDENTS REPRESENTED</p>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>"
    block:
      variations: 'center nopaddingall'
  custom-3719:
    title: 'Custom HTML'
    attributes:
      html: '<h2 class="g-title">History</h2>'
    block:
      id: history
      variations: title-center
  contenttabs-3854:
    title: History
    attributes:
      animation: toggle
      items:
        -
          content: '<p>Science and engineering students met at Universite Laval for the Congress of Science and Engineering Students of Quebec. During the plenary session there was much discussion about the engineer’s role in society and the possibility of developing an opportunity to reassemble engineering students to address the issue.</p>'
          title: '1967'
        -
          content: "<p>The Layout Manager makes it easier than ever to arrange and customize your users’ experience with drag-and-drop simplicity from start to finish. A handful of the many features found in the Layout Manager are listed below.</p>\n<div class=\"g-grid size-100\">\n    <div class=\"g-block size-50\">\n        <ul>\n            <li>Drag-and-drop Functionality</li>\n            <li>Unlimited Items Per Row</li>\n            <li>Unlimited Rows Per Section</li>\n            <li>Easy Widget Position Placement</li>\n            <li>Resize Items with Simple Sliders</li>\n            <li>Per-section CSS Classes and Tag Attributes</li>\n        </ul>\n    </div>\n    <div class=\"g-block size-50\">\n        <ul>\n            <li>Per-block CSS Classes, Variations, and Tag Attributes</li>\n            <li>Quick Preset Loading</li>\n            <li>Undo and Redo</li>\n            <li>Access to Easy-to-use Particles</li>\n            <li>Intuitive Visual Interface</li>\n            <li>Touch-screen Friendly</li>\n        </ul>\n    </div>\n</div>\n<div>Find out more about using the Layout Manager in our <a href=\"http://docs.gantry.org/gantry5/configure/layout-manager\">documentation</a>.</div>"
          title: '1969'
        -
          content: ''
          title: '1977'
        -
          content: ''
          title: '1988'
        -
          content: ''
          title: '1992'
        -
          content: ''
          title: '1994'
        -
          title: '1997'
        -
          title: '2015'
