name: conference_on_diversity_in_engineering
timestamp: 1494951805
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-1773: 'Owl Carousel'
  custom:
    custom-5132: 'Current Year Host Info'
    custom-2267: Intro
    custom-5763: 'Custom HTML'
    custom-4867: 'Past hosts'
    custom-3794: stats
  widget:
    position-widget-1440: Widget
    position-widget-8246: ABOUT
    position-widget-9246: 'events & services'
    position-widget-3930: Resources
    position-widget-6015: Widget
  logo:
    logo-5397: 'Logo / Image'
  menu:
    menu-3825: Menu
  social:
    social-1045: Social
  copyright:
    copyright-3158: Copyright
  totop:
    totop-6966: 'To Top'
  mobile-menu:
    mobile-menu-4615: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-5397: logo-9608
    menu-3825: menu-6409
    social-1045: social-3171
    position-widget-8246: position-widget-5932
    position-widget-9246: position-widget-1245
    position-widget-3930: position-widget-2815
    position-widget-6015: position-widget-1915
    copyright-3158: copyright-1736
    totop-6966: totop-8670
    mobile-menu-4615: mobile-menu-5697
  about:
    utility: utility
    mainbar: mainbar
    sidebar: sidebar
    custom-3794: custom-2396
  canadian_engineering_competition:
    above: above
