name: members
timestamp: 1494636074
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-4030: 'Page Content'
  logo:
    logo-3181: 'Logo / Image'
  menu:
    menu-1317: Menu
  social:
    social-6659: Social
  widget:
    position-widget-5619: ABOUT
    position-widget-1521: 'events & services'
    position-widget-9782: Resources
    position-widget-8970: Widget
  copyright:
    copyright-8975: Copyright
  totop:
    totop-6186: 'To Top'
  mobile-menu:
    mobile-menu-9942: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    footer: footer
    offcanvas: offcanvas
    logo-3181: logo-9608
    menu-1317: menu-6409
    social-6659: social-3171
    position-widget-5619: position-widget-5932
    position-widget-1521: position-widget-1245
    position-widget-9782: position-widget-2815
    position-widget-8970: position-widget-1915
    copyright-8975: copyright-1736
    totop-6186: totop-8670
    mobile-menu-9942: mobile-menu-5697
  officers:
    system-content-4030: system-content-9070
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
