name: partners
timestamp: 1494169276
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-1420: 'Engineers Canada'
  logo:
    logo-2331: 'Logo / Image'
  menu:
    menu-2502: Menu
  social:
    social-6901: Social
  widget:
    position-widget-7198: ABOUT
    position-widget-5713: 'events & services'
    position-widget-1863: Resources
    position-widget-2072: Widget
  copyright:
    copyright-8857: Copyright
  totop:
    totop-8710: 'To Top'
  mobile-menu:
    mobile-menu-6083: Mobile-menu
inherit:
  default:
    navigation: navigation
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    footer: footer
    offcanvas: offcanvas
    logo-2331: logo-9608
    menu-2502: menu-6409
    social-6901: social-3171
    position-widget-7198: position-widget-5932
    position-widget-5713: position-widget-1245
    position-widget-1863: position-widget-2815
    position-widget-2072: position-widget-1915
    copyright-8857: copyright-1736
    totop-8710: totop-8670
    mobile-menu-6083: mobile-menu-5697
