version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493084029
layout:
  navigation: {  }
  /header/: {  }
  /intro/:
    -
      - custom-1420
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 75': {  }
      -
        'mainbar 20': {  }
      -
        'sidebar 5': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#f0f0f0;'
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      extra:
        -
          style: 'display:none;'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  custom-1420:
    title: 'Engineers Canada'
    attributes:
      html: " <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">Engineers Canada</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n                </div>\n </div>\n        "
    block:
      variations: box2
