name: congress
timestamp: 1494951805
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-9628: 'Owl Carousel'
  custom:
    custom-1542: 'Current Year Host Info'
    custom-4849: Intro
    custom-8079: 'Custom HTML'
    custom-8169: 'Past hosts'
    custom-7127: stats
  widget:
    position-widget-3082: Widget
    position-widget-4756: ABOUT
    position-widget-4049: 'events & services'
    position-widget-3398: Resources
    position-widget-6038: Widget
  logo:
    logo-1039: 'Logo / Image'
  menu:
    menu-7829: Menu
  social:
    social-2399: Social
  copyright:
    copyright-2692: Copyright
  totop:
    totop-3840: 'To Top'
  mobile-menu:
    mobile-menu-6194: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-1039: logo-9608
    menu-7829: menu-6409
    social-2399: social-3171
    position-widget-4756: position-widget-5932
    position-widget-4049: position-widget-1245
    position-widget-3398: position-widget-2815
    position-widget-6038: position-widget-1915
    copyright-2692: copyright-1736
    totop-3840: totop-8670
    mobile-menu-6194: mobile-menu-5697
  about:
    utility: utility
    mainbar: mainbar
    sidebar: sidebar
    custom-7127: custom-2396
  canadian_engineering_competition:
    above: above
    custom-8079: custom-2888
