name: contact
timestamp: 1494172259
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493084029
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8858: 'Logo / Image'
  menu:
    menu-8384: Menu
  social:
    social-8097: Social
  content:
    system-content-9239: 'Page Content'
    system-content-7772: 'Page Content'
  position:
    position-position-4552: Aside
    position-position-1109: Sidebar
  widget:
    position-widget-7808: ABOUT
    position-widget-7630: 'events & services'
    position-widget-7103: Resources
    position-widget-4449: Widget
  copyright:
    copyright-3724: Copyright
  totop:
    totop-3126: 'To Top'
  mobile-menu:
    mobile-menu-8723: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-8858: logo-9608
    menu-8384: menu-6409
    social-8097: social-3171
    header: header
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    system-content-7772: system-content-1587
    mainbar: mainbar
    position-position-4552: position-position-4734
    sidebar: sidebar
    position-position-1109: position-position-3949
    footer: footer
    position-widget-7808: position-widget-5932
    position-widget-7630: position-widget-1245
    position-widget-7103: position-widget-2815
    position-widget-4449: position-widget-1915
    copyright-3724: copyright-1736
    totop-3126: totop-8670
    offcanvas: offcanvas
    mobile-menu-8723: mobile-menu-5697
