name: best_courses
timestamp: 1494951805
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-9411: 'Owl Carousel'
  custom:
    custom-4716: 'Current Year NEM Info'
    custom-2524: Intro
    custom-4608: stats
    custom-2565: 'Custom HTML'
    custom-3118: 'Competition Categories Title'
    custom-7245: 'Junior Design'
    custom-8960: 'Senior Design'
    custom-3656: 'Innovative Design'
    custom-5652: Communications
    custom-8404: Consulting
    custom-6222: RE-ENGINEERING
    custom-1320: 'Custom HTML'
    custom-7918: DEBATE
    custom-9512: 'Custom HTML'
    custom-2859: 'Past hosts'
  widget:
    position-widget-7000: Widget
    position-widget-6807: ABOUT
    position-widget-7320: 'events & services'
    position-widget-4848: Resources
    position-widget-1441: Widget
  logo:
    logo-5724: 'Logo / Image'
  menu:
    menu-1191: Menu
  social:
    social-5622: Social
  copyright:
    copyright-1650: Copyright
  totop:
    totop-1864: 'To Top'
  mobile-menu:
    mobile-menu-9040: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-5724: logo-9608
    menu-1191: menu-6409
    social-5622: social-3171
    position-widget-6807: position-widget-5932
    position-widget-7320: position-widget-1245
    position-widget-4848: position-widget-2815
    position-widget-1441: position-widget-1915
    copyright-1650: copyright-1736
    totop-1864: totop-8670
    mobile-menu-9040: mobile-menu-5697
  about:
    utility: utility
    mainbar: mainbar
    sidebar: sidebar
    custom-4608: custom-2396
  canadian_engineering_competition:
    above: above
  lean_6_sigma:
    testimonials: testimonials
    custom-2565: custom-3613
  international_engineering_competition:
    expanded: expanded
    custom-3118: custom-1806
    custom-7245: custom-3445
    custom-8960: custom-4513
    custom-3656: custom-3002
    custom-5652: custom-1909
    custom-8404: custom-3590
    custom-6222: custom-9733
    custom-1320: custom-9419
    custom-7918: custom-3429
    custom-9512: custom-9340
    custom-2859: custom-7274
