version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - custom-5807
  /features/:
    -
      - custom-3119
  /utility/:
    -
      - custom-2396
  /above/:
    -
      - custom-6355
    -
      - position-widget-8277
  /testimonials/:
    -
      - custom-7658
  /expanded/:
    -
      - 'custom-5349 25'
      - 'custom-7568 25'
      - 'custom-3774 25'
      - 'custom-1444 25'
    -
      - 'custom-1036 25'
      - 'custom-3554 25'
      - 'custom-3998 25'
      - 'custom-7674 25'
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
      extra:
        -
          style: 'max-height:650px;'
  intro:
    type: section
    attributes:
      boxed: ''
      class: nopaddingall
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'padding:1.5rem 0;'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'display:none;'
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#f0f0f0;'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      items:
        -
          image: 'gantry-media://header/img01.jpg'
          title: 'Congress 2017, London Ontario'
          desc: 'Hosted by Western University on January 2-7, 2017'
          link: 'blog post -1'
          linktext: 'Read More'
          buttonclass: button-outline
          name: 'Item 1'
        -
          image: 'gantry-media://header/img02.jpg'
          title: 'Helium is Gantry powered!'
          desc: 'Helium is based on the powerful Gantry framework.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: button-outline
          name: 'Item 2'
  custom-5807:
    title: 'Mission Statement'
    attributes:
      html: "<div class=\"fp-intro\">\n    <h2 class=\"g-title\">Supporting the growth and communication for engineering students</h2>\n    <p>to ensure their moral, intellectual,  cultural, academic, social and economic well-being.</p>\n    <!---<div class=\"ipad-mockup\">\n        <img src=\"gantry-media://intro/mockup.png\" alt=\"\" />\n    </div>-->\n</div>"
    block:
      variations: center
      extra:
        -
          style: 'padding-top:1rem;'
  custom-3119:
    title: 'Main Points'
    attributes:
      html: "<div class=\"fp-features\">\n    <div class=\"g-grid\">\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-joomla\"></i>\n                    <h4 class=\"card-title\">Who We Are</h4>\n                    <p class=\"card-text\">CFES is a student run words words words words words words words words words words words words words words</p>\n<br><br><a class=\"g-owlcarousel-item-button button button-outline\" href=\"_self\">Read More About Us</a>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-wordpress\"></i>\n                    <h4 class=\"card-title\">What We Do</h4>\n                    <p class=\"card-text\">CFES is a student run words words words words words words words words words words words words words words</p>\n<br><br><a class=\"g-owlcarousel-item-button button button-outline\" href=\"_self\">See What We Offer</a>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-grav\"></i>\n                    <h4 class=\"card-title\">Get Involved</h4>\n                    <p class=\"card-text\">CFES is a student run words words words words words words words words words words words words words words</p>\n<br><br><a class=\"g-owlcarousel-item-button button button-outline\" href=\"_self\">See Who We Represent</a>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>"
    block:
      variations: center
  custom-2396:
    title: stats
    attributes:
      html: "<div class=\"fp-features\">\n    <div class=\"g-grid\">\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">52</h4>\n                    <p class=\"card-text\">REPRESENTED MEMBER SOCIETIES</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">8</h4>\n                    <p class=\"card-text\">ANNUAL EVENTS & SERVICES</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">48</h4>\n                    <p class=\"card-text\">YEARS OF OPERATION</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-25\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <h4 class=\"card-title\">60,000</h4>\n                    <p class=\"card-text\">STUDENTS REPRESENTED</p>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>"
    block:
      variations: 'center nopaddingall'
  custom-6355:
    title: 'Featured Posts'
    attributes:
      html: "    <h2 class=\"g-title\">Featured Posts</h2>\n    "
    block:
      variations: 'title-center nopaddingall nomarginall'
  position-widget-8277:
    attributes:
      widget: '{"type":"widget","widget":"cfp-widget","title":"Featured Posts","options":{"widget":{"category":"","taxonomy":"","post_type":"post","post_num":6,"offset":0,"post_id":0,"template":"fancy","cols_xs":1,"cols_sm":1,"cols_md":3,"title":""}}}'
      key: widget
    block:
      variations: title-center
  custom-7658:
    title: 'Customer Testimonials (hidden)'
    attributes:
      html: "<div class=\"fp-testimonials\">\n    <blockquote>\n        <img src=\"gantry-media://testimonials/face.jpg\" alt=\"Avatar\" class=\"g-img-circle\" height=\"80\" width=\"80\">\n        <p class=\"h3\">\"Helium is a beautiful, free theme made by the RocketTheme team in appreciation of the incredible Gantry community.\"</p>\n        <footer>Andy Miller</footer>\n    </blockquote>\n</div>"
    block:
      variations: center
      extra:
        -
          style: 'display:none;'
  custom-5349:
    title: Congress
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-7568:
    title: CEC
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-3774:
    title: IEC
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-1444:
    title: NEM
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-1036:
    title: 'Lean 6'
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-3554:
    title: CDE
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-3998:
    title: PM
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
  custom-7674:
    title: BEST
    attributes:
      html: "           <a href=\"#\" class=\"event-card\"> <div class=\"card\">\n                <div class=\"card-block\">\n                    <h3 class=\"card-title\">CANADIAN ENGINEERING COMPETITION</h3>\n                   <hr>\n                    <p class=\"card-text\">description</p>\n<p class=\"button\"> Learn More </p>\n                </div>\n            </div></a>\n        "
    block:
      variations: box2
