version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493058262
layout:
  /header/:
    -
      - 'logo-1521 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-1142
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-6041
    -
      - system-content-4873
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3693 40'
      - 'spacer-9967 30'
      - 'branding-8370 30'
  offcanvas:
    -
      - mobile-menu-1914
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
