name: canadian_engineering_competition
timestamp: 1494951805
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1493084029
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-5024: 'Owl Carousel'
  custom:
    custom-5313: 'Current Year Host Info'
    custom-2141: Intro
    custom-2888: 'Custom HTML'
    custom-2622: 'Competition Categories Title'
    custom-3574: 'Junior Design'
    custom-9055: 'Senior Design'
    custom-4987: 'Innovative Design'
    custom-8008: Communications
    custom-6664: Consulting
    custom-9139: RE-ENGINEERING
    custom-4040: 'Custom HTML'
    custom-9081: DEBATE
    custom-3043: 'Custom HTML'
    custom-1384: 'Past hosts'
    custom-7551: stats
  widget:
    position-widget-8009: Widget
    position-widget-8724: ABOUT
    position-widget-3732: 'events & services'
    position-widget-7932: Resources
    position-widget-6533: Widget
  logo:
    logo-5089: 'Logo / Image'
  menu:
    menu-1283: Menu
  social:
    social-3639: Social
  copyright:
    copyright-7184: Copyright
  totop:
    totop-3205: 'To Top'
  mobile-menu:
    mobile-menu-8455: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-5089: logo-9608
    menu-1283: menu-6409
    social-3639: social-3171
    position-widget-8724: position-widget-5932
    position-widget-3732: position-widget-1245
    position-widget-7932: position-widget-2815
    position-widget-6533: position-widget-1915
    copyright-7184: copyright-1736
    totop-3205: totop-8670
    mobile-menu-8455: mobile-menu-5697
  about:
    utility: utility
    mainbar: mainbar
    sidebar: sidebar
    custom-7551: custom-2396
