name: _offline
timestamp: 1493058265
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493058262
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1411: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4488: Menu
  messages:
    system-messages-5874: 'System Messages'
  content:
    system-content-2073: 'Page Content'
  copyright:
    copyright-4545: Copyright
  spacer:
    spacer-5946: Spacer
  branding:
    branding-9266: Branding
  mobile-menu:
    mobile-menu-1518: Mobile-menu
inherit: {  }
